# Generated by Django 5.1.7 on 2025-04-08 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsa_tutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatthread',
            unique_together={('chatbot', 'owner')},
        ),
    ]
